spring:
  # 远程数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.142.93.28/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: admin123
  redis:
    host: 43.142.93.28
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s